// cargo-fuzz target for the `-iL` / `--excludefile` tokenizer and the exclusion
// matcher — `nmap_core::targets::{host_specs, exclude_specs, ExcludeSet}`.
//
// Why this target exists, and why only now: M7.2 reconciled the gate tracker and
// deliberately left `options` short of the `fuzzed` gate rather than exempting it,
// with the reason written down — "argv is operator-supplied, which is the usual
// argument for exempting it, but M7.3 adds -iL and --excludefile, which read
// *files*. Exempting it now would be exempting it one milestone before the
// premise stops holding." M7.4 implemented those two flags, so the premise has
// now stopped holding and this is the coverage that was promised.
//
// The input that matters is a list FILE. It is operator-supplied in the sense
// that the operator names the path, but its contents routinely are not: target
// lists are generated by other tooling, pulled from inventories, or handed over
// by whoever asked for the scan. Treating it as untrusted is the honest posture.
//
// Totality is necessary but not sufficient here, for the same reason it was not
// for `osprobe_demux`: the damage from a wrong answer is worse than from no
// answer. An exclusion that silently fails to apply scans the host the operator
// took an explicit step to protect — the M7.0 bug — and there is no error path,
// just a host that quietly gets scanned. So this asserts the structural contract
// of the tokenizer and the one invariant the whole feature exists to provide.
#![no_main]

use libfuzzer_sys::fuzz_target;
use nmap_core::targets::{exclude_specs, host_specs, Added, ExcludeSet, HostListError};
use std::net::{IpAddr, Ipv4Addr};

/// Split the fuzzer's bytes into a list-file half and an `--exclude` half, so a
/// single input drives both parsers and their interaction rather than one each.
fn split(data: &[u8]) -> (&[u8], &[u8]) {
    let at = data.first().map_or(0, |b| usize::from(*b)).min(data.len());
    data.split_at(at)
}

fuzz_target!(|data: &[u8]| {
    let (list_bytes, exclude_bytes) = split(data);

    // --- the tokenizer -------------------------------------------------------
    // Total over arbitrary bytes, and deterministic.
    let first = host_specs(list_bytes);
    assert_eq!(
        first.is_ok(),
        host_specs(list_bytes).is_ok(),
        "host_specs is not deterministic"
    );

    if let Ok(specs) = &first {
        for (i, tok) in specs.iter().enumerate() {
            // A token may never contain a separator or a '#'. If it could, the
            // tokenizer has merged two specs into one, and a merged spec parses
            // as a hostname — so "10.0.0.1 10.0.0.2" would become a single name
            // that fails to resolve, and BOTH hosts would silently vanish from
            // the scan. Silent under-scanning is the quieter failure, but it is
            // still the scanner not doing what it was told.
            assert!(
                !tok.contains([' ', '\r', '\n', '\t', '\0', '#']),
                "token {i} {tok:?} contains a separator"
            );
            // The C's bound is `n >= 1024`; anything at or past it is an Err,
            // never a truncated spec.
            assert!(
                tok.len() < nmap_core::targets::MAX_HOST_SPEC,
                "token {i} is {} bytes, which should have been SpecTooLong",
                tok.len()
            );
        }
    }

    // An error must name a token index that could exist.
    match first {
        Err(HostListError::SpecTooLong { index } | HostListError::NotUtf8 { index }) => {
            // Nothing stronger is available without re-tokenizing, but the index
            // must at least be a plausible position rather than a sentinel.
            assert!(index < list_bytes.len().saturating_add(1));
        }
        Ok(_) => {}
    }

    // --- the exclusion matcher ----------------------------------------------
    let Ok(exclude_text) = std::str::from_utf8(exclude_bytes) else {
        return;
    };

    let mut set = ExcludeSet::new();
    let mut added_any = false;
    for spec in exclude_specs(exclude_text) {
        match set.add(spec, false) {
            Ok(Added::Numeric) => added_any = true,
            // A name is handed back for the caller to resolve, never stored.
            // The CLI refuses the scan if it cannot resolve it; here we only
            // check the contract that it did not silently enter the set.
            Ok(Added::NeedsResolution(_)) => {}
            Err(_) => {}
        }
    }

    // An empty set excludes nothing — the filter must be a no-op, not a
    // match-everything. Getting this backwards would silently scan zero hosts.
    if !added_any && set.is_empty() {
        for probe in [
            Ipv4Addr::new(127, 0, 0, 1),
            Ipv4Addr::new(10, 0, 0, 1),
            Ipv4Addr::new(255, 255, 255, 255),
        ] {
            assert!(
                !set.contains(IpAddr::V4(probe)),
                "an empty exclude set matched {probe}"
            );
        }
    }

    // Deterministic membership: the same address must answer the same way twice.
    // A set built from attacker-shaped specs answering inconsistently would make
    // exclusion depend on iteration order.
    let probe = IpAddr::V4(Ipv4Addr::new(
        list_bytes.first().copied().unwrap_or(10),
        list_bytes.get(1).copied().unwrap_or(0),
        list_bytes.get(2).copied().unwrap_or(0),
        list_bytes.get(3).copied().unwrap_or(1),
    ));
    assert_eq!(
        set.contains(probe),
        set.contains(probe),
        "ExcludeSet::contains is not deterministic"
    );

    // --- THE invariant the feature exists for --------------------------------
    // Filter a target list exactly as the CLI does, then assert that nothing
    // which survived is excluded. This is the property the M7.0 bug violated,
    // stated in the one place a fuzzer can attack it from every direction.
    if let Ok(specs) = &first {
        let mut survivors: Vec<IpAddr> = Vec::new();
        for spec in specs.iter().take(64) {
            if let Ok(nmap_core::TargetSpec::Ipv4(ranges)) = nmap_core::parse_target(spec, false) {
                // Bounded: a spec may cover 2^32 addresses and this runs per input.
                for ip in ranges.iter().take(256) {
                    survivors.push(IpAddr::V4(ip));
                }
            }
        }
        survivors.retain(|ip| !set.contains(*ip));
        for ip in survivors {
            assert!(
                !set.contains(ip),
                "{ip} survived the exclusion filter but is excluded"
            );
        }
    }
});
