#!/usr/bin/env python3
"""Generate the IPv6 probe-battery corpus for core::build6.

Each line is one full set of `FPHost6::build_probe_list()` inputs; the oracle emits the
17 probes nmap builds for it, and the Rust builder must match byte for byte.

The interesting axes are the ones that change packet bytes rather than just values:
port availability (a missing open or closed TCP port silently drops probes), the
hop limit, whether the target is directly connected (which gates the NS probe), and
addresses of different shapes (the checksum folds every byte of both).

Deterministic: fixed seed, so the committed golden is reproducible.

  ./gen_build6_cases.py
  ./build6_oracle < ../build6_cases.txt > ../build6_golden.txt
"""
import os
import random

OUT = os.path.join(os.path.dirname(__file__), "..", "build6_cases.txt")
SEED = 0x6B111D6
COUNT = 400

ADDRS = [
    "2001:db8::1", "2001:db8::2", "fe80::1", "fe80::dead:beef",
    "::1", "2001:4860:4860::8888", "fd00:1234:5678:9abc::1",
    "2606:4700:4700::1111", "::ffff:192.0.2.1", "2001:db8:0:0:8:800:200c:417a",
]


def main():
    rnd = random.Random(SEED)
    lines = []

    # A fixed, fully-populated baseline: every probe present, easy to eyeball.
    lines.append("2001:db8::1 2001:db8::2 22 1 42 33000 34000 305419896 64 4660 1 "
                 + " ".join(str(100 + i) for i in range(13)))

    for _ in range(COUNT - 1):
        src = rnd.choice(ADDRS)
        dst = rnd.choice(ADDRS)
        # -1 for a port means "we never found one", which drops whole probes.
        open_tcp = rnd.choice([-1, 22, 80, 443, 65535, rnd.randrange(1, 65536)])
        closed_tcp = rnd.choice([-1, 1, 9, 33333, rnd.randrange(1, 65536)])
        closed_udp = rnd.choice([1, 42, 53, 40125, rnd.randrange(1, 65536)])
        tcp_base = rnd.randrange(1, 65500 - 13)
        udp_base = rnd.randrange(1, 65535)
        # Exercise the u32 wrap in tcpSeqBase + i.
        seq = rnd.choice([0, 1, 0xFFFFFFF8, 0xFFFFFFFF, rnd.randrange(0, 1 << 32)])
        # get_hoplimit() is o.ttl or (random % 23) + 37; 255 is the NS special case.
        hoplimit = rnd.choice([1, 37, 59, 64, 128, 255, rnd.randrange(1, 256)])
        icmp_seq = rnd.choice([0, 1, 0xFFFF, rnd.randrange(0, 1 << 16)])
        connected = rnd.choice([0, 1])
        acks = [rnd.choice([0, 1, 0xFFFFFFFF, rnd.randrange(0, 1 << 32)])
                for _ in range(13)]
        lines.append(f"{src} {dst} {open_tcp} {closed_tcp} {closed_udp} "
                     f"{tcp_base} {udp_base} {seq} {hoplimit} {icmp_seq} {connected} "
                     + " ".join(str(a) for a in acks))

    with open(OUT, "w") as f:
        f.write(f"# generated by gen_build6_cases.py, seed 0x{SEED:X}, {len(lines)} cases\n")
        f.write("# src dst open_tcp closed_tcp closed_udp tcp_base udp_base "
                "seqbase hoplimit icmp_seq directly_connected ack0..ack12\n")
        for line in lines:
            f.write(line + "\n")
    print(f"wrote {len(lines)} build6 cases to {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
