#!/usr/bin/env python3
"""Generate the M6.3 differential corpus: `--script-args` -> nmap.registry.args.

The oracle is nmap's own Lua and LPeg (`build_lua_oracle.sh`), running the
argument-joining code and the grammar sliced verbatim out of `nse_main.lua`
and `nselib/lpeg-utility.lua` by `extract_nse_main.py`. Nothing about how an
argument string parses is restated here; only the CASES are ours:

  A. corners, each a decision in the grammar (empty strings, the missing end
     anchor, quoting and escapes, whitespace, repeated keys, nesting);
  B. every `--script-args` example in the shipped scripts' and libraries'
     documentation, as written there;
  C. every string of up to four bytes over the grammar's alphabet
     (`a`, space, tab, newline, `,`, `=`, `{`, `}`, `"`, `'`, `\\`);
  D. a seeded sweep of longer strings over the same alphabet plus a few bytes
     the grammar treats as plain (`x`, `.`, `-`, a high byte, NUL);
  E. a `--script-args-file` with and without `--script-args`: trailing commas,
     blank files, newlines;
  F. nesting depth along each path (bare values, keyed values, list siblings)
     to past the point where LPeg's 100-slot stack gives out.

Output, in the directory given as argv[1]:
  m63_args_cases.txt   name<TAB>file_hex or -<TAB>cli_hex<TAB>note
  m63_args_golden.txt  name<TAB>verdict, where verdict is `ok<TAB>rendering`,
                       `nomatch`, or `error:backtrack`

A rendering is canonical: `{` positional values in order, then `key=value` in
bytewise key order, comma-separated, `}`; a string is `s` and its hex.
"""

import os
import random
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import extract_nse_main as ex  # noqa: E402

ROOT = os.path.normpath(os.path.join(HERE, "..", "..", "..", "..", ".."))
LUA = os.path.join(HERE, "lua")


def build_driver():
    blocks = ex.extract_m63(ROOT)
    digest = ex.provenance(blocks)

    def text(name):
        return blocks[name][0]

    def where(name):
        _, first, last = blocks[name]
        src = ex.LPEG_UTILITY if name in ex.M63_LPEG_UTILITY_BLOCKS else ex.NSE_MAIN
        return f"{src}:{first}-{last}"

    return "".join([
        "-- GENERATED by oracle/gen_m63_args.py. Do not edit.\n",
        f"-- Provenance digest over all extracted blocks: {digest}\n\n",
        'local lpeg = require "lpeg"\n',
        "local locale, P, S, V, C, Cf, Cg, Ct = lpeg.locale, lpeg.P, lpeg.S, lpeg.V, lpeg.C, lpeg.Cf, lpeg.Cg, lpeg.Ct\n",
        "local concat, insert = table.concat, table.insert\n",
        "local function print_debug() end\n\n",
        f"-- VERBATIM {where('escaped_quote')}\n",
        text("escaped_quote") + "\n",
        "local U = { escaped_quote = escaped_quote }\n\n",
        "local function registry_args (file, cli)\n",
        "  local nmap = { registry = { args = {} } }\n",
        "  local cnse = { scriptargs = cli }\n",
        "  local args = {}\n",
        "  if file then\n",
        "    local path = 'args-file'\n",
        "    local function open () return { read = function () return file end } end\n",
        f"  -- VERBATIM {where('script_args_file')}\n",
        text("script_args_file") + "\n",
        "  end\n",
        f"  -- VERBATIM {where('script_args_cli')}\n",
        text("script_args_cli") + "\n",
        f"  -- VERBATIM {where('script_args_parse')}\n",
        text("script_args_parse") + "\n",
        "  end -- closes `if #args > 0 then` above\n",
        "  return nmap.registry.args\n",
        "end\n",
        r'''
local function hex (s)
  return (s:gsub(".", function (c) return string.format("%02x", c:byte()) end))
end
local function unhex (s)
  return (s:gsub("%x%x", function (b) return string.char(tonumber(b, 16)) end))
end

local function render (v)
  if type(v) == "string" then return "s" .. hex(v) end
  local parts, keys = {}, {}
  for i = 1, #v do parts[#parts + 1] = render(v[i]) end
  for k in pairs(v) do
    if type(k) ~= "number" then keys[#keys + 1] = k
    elseif k < 1 or k > #v or k % 1 ~= 0 then error("non-sequence key") end
  end
  table.sort(keys)
  for _, k in ipairs(keys) do parts[#parts + 1] = hex(k) .. "=" .. render(v[k]) end
  return "{" .. table.concat(parts, ",") .. "}"
end

for line in io.lines() do
  local name, file_hex, cli_hex = line:match("^([^\t]+)\t([^\t]*)\t([^\t]*)")
  local file = file_hex ~= "-" and unhex(file_hex) or nil
  local ok, res = pcall(registry_args, file, unhex(cli_hex))
  if not ok then
    if tostring(res):find("too many pending calls/choices", 1, true) then
      io.write(name, "\terror:backtrack\n")
    else
      io.write(name, "\terror:other ", tostring(res), "\n")
    end
  elseif res == nil then
    io.write(name, "\tnomatch\n")
  else
    io.write(name, "\tok\t", render(res), "\n")
  end
end
''',
    ]), digest


CASES = []
_seen = set()


def add(name, cli, note, file=None):
    if name in _seen:
        raise SystemExit("duplicate case: " + name)
    _seen.add(name)
    CASES.append((name, file, cli.encode("latin-1") if isinstance(cli, str) else cli, note))


def gen():
    # A. corners
    corners = [
        ("empty", "", "no arguments at all: an empty table"),
        ("blank", " ", "a blank string is one empty value"),
        ("comma", ",", "two empty values"),
        ("empty_between", "a,,b", "an empty value between commas"),
        ("empty_table", "a={}", "{} is a table holding one empty string"),
        ("no_end_anchor", "a=1},junk", "text after the closing brace is ignored"),
        ("inner_space", "x = y z  ,w", "inner spaces kept, outer dropped"),
        ("quoted_key", '"a\\"b"=c', "an escaped quote in a quoted key"),
        ("single_quoted", "'q'", "single quotes"),
        ("quote_then_brace", 'a="}', "an unterminated quote is an unquoted string"),
        ("open_brace", "a={", "an unclosed table does not parse"),
        ("double_eq", "k=v=w", "a second '=' does not parse"),
        ("nested_list", "{x}", "a positional table"),
        ("space_in_key", "a b=c", "a key with a space"),
        ("empty_key", "=x", "an empty key"),
        ("repeated_key", "a=1,a=2", "the last assignment wins"),
        ("numeric_key", "1=x,y", "a numeric key stays a string"),
        ("newline_sep", "a\nb", "newline separates fields"),
        ("tab_key", "a\tb = c\t", "tabs are horizontal whitespace"),
        ("backslash_kept", '"a\\xb"', "a backslash before a plain byte is kept"),
        ("backslash_escaped", '"a\\\\b"', "a doubled backslash is one"),
        ("backslash_end", '"a\\', "a lone backslash before the end"),
        ("quote_after_value", '"a"b=c', "text after a quoted key does not parse"),
        ("cr_lf", "a=1\r\nb=2", "CR is horizontal whitespace, LF separates"),
        ("vt_ff", "a\x0b=\x0c1", "VT and FF are whitespace"),
        ("high_bytes", "k=\xff\xfe", "bytes above 0x7f are plain"),
        ("nul_byte", "k=a\x00b", "a NUL is a plain byte"),
        ("leading_comma", ",a", "a leading empty value"),
        ("trailing_comma", "a,", "a trailing empty value"),
        ("sep_space_newline", "a ,\n b", "whitespace around separators"),
        ("table_value_key", "k={a=1,b={c}}", "nested keyed tables"),
        ("table_after_close", "a={x}y", "text after a nested table does not parse"),
        ("brace_in_quotes", 'k="{}=,"', "delimiters inside quotes are plain"),
        ("eq_in_single", "k='a=b'", "'=' inside single quotes"),
        ("mixed_quotes", "k=\"it's\"", "a single quote inside double quotes"),
        ("only_spaces_table", "k={   }", "a blank nested table"),
        ("closing_only", "}", "a stray closing brace ends the table"),
        ("closing_then_text", "},x", "and the rest is ignored"),
    ]
    for name, cli, note in corners:
        add("corner_" + name, cli, note)

    # B. documented examples
    pat = re.compile(r"--script-args[= ]*(\"[^\"]*\"|'[^']*'|[^ \n]*)")
    examples = set()
    for sub in ("scripts", "nselib"):
        d = os.path.join(ROOT, sub)
        for fn in sorted(f for f in os.listdir(d) if f.endswith((".nse", ".lua"))):
            with open(os.path.join(d, fn), encoding="latin-1") as fh:
                for m in pat.finditer(fh.read()):
                    arg = m.group(1)
                    if len(arg) >= 2 and arg[0] == arg[-1] and arg[0] in "\"'":
                        arg = arg[1:-1]  # the shell's quotes
                    examples.add(arg)
    for i, arg in enumerate(sorted(examples)):
        add("doc_%03d" % i, arg, "documented example")

    # C. exhaustive short strings
    alphabet = ["a", " ", "\t", "\n", ",", "=", "{", "}", '"', "'", "\\"]
    names = ["a", "sp", "tab", "nl", "comma", "eq", "lb", "rb", "dq", "sq", "bs"]

    def rec(prefix, label, n):
        if prefix:
            add("short_" + label, prefix, "exhaustive short string")
        if n == 0:
            return
        for c, nm in zip(alphabet, names):
            rec(prefix + c, (label + "_" if label else "") + nm, n - 1)
    rec("", "", 4)

    # D. seeded sweep
    rng = random.Random(0x63A)
    wide = alphabet + ["x", ".", "-", "\xe9", "\x00", "b", "c"]
    weights = [6, 3, 1, 1, 3, 3, 2, 2, 2, 1, 1, 4, 1, 1, 1, 1, 3, 3]
    for i in range(4000):
        n = rng.randint(5, 24)
        s = "".join(rng.choices(wide, weights, k=n))
        add("sweep_%04d" % i, s, "seeded sweep")

    # E. files
    files = [
        ("plain", "a=1"), ("trailing_commas", "a=1,,,"), ("newline_end", "a=1,,\n"),
        ("blank", ""), ("only_commas", ",,,"), ("multi_line", "a=1\nb={x,y}\n"),
        ("crlf", "a=1\r\nb=2\r\n"), ("bad", "a={"), ("quoted", "k='v,w'"),
    ]
    clis = [("none", ""), ("kv", "b=2"), ("same_key", "a=9"), ("bad", "x=y=z")]
    for fn, content in files:
        for cn, cli in clis:
            add("file_%s_cli_%s" % (fn, cn), cli, "--script-args-file with --script-args",
                file=content.encode("latin-1"))

    # F. depth along each path
    for n in range(1, 21):
        add("depth_av_%02d" % n, "{" * n + "x" + "}" * n, "nested positional tables")
        add("depth_kv_%02d" % n, "".join("k%d={" % i for i in range(n)) + "x" + "}" * n,
            "nested keyed tables")
        add("depth_sib_%02d" % n, "a,{" * n + "x" + "}" * n, "nested tables after a sibling")
        add("depth_q_%02d" % n, "{" * n + '"x"' + "}" * n, "nested, with a quoted leaf")


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "."
    driver, digest = build_driver()
    gen()
    driver_path = os.path.join(out, "m63_args_driver.lua")
    with open(driver_path, "w", encoding="utf-8") as fh:
        fh.write(driver)
    lines = ["%s\t%s\t%s" % (n, f.hex() if f is not None else "-", c.hex()) for n, f, c, _ in CASES]
    r = subprocess.run([LUA, driver_path], input="\n".join(lines) + "\n",
                       capture_output=True, text=True, encoding="latin-1", check=True)
    os.unlink(driver_path)
    with open(os.path.join(out, "m63_args_cases.txt"), "w", encoding="latin-1") as fh:
        fh.write("# name\tfile_hex\tcli_hex\tnote\n")
        fh.write("# Generated by oracle/gen_m63_args.py; regenerate with ./regen_m63.sh.\n")
        for n, f, c, note in CASES:
            fh.write("%s\t%s\t%s\t%s\n" % (n, f.hex() if f is not None else "-", c.hex(), note))
    with open(os.path.join(out, "m63_args_golden.txt"), "w", encoding="latin-1") as fh:
        fh.write("# name\tverdict\n")
        fh.write(f"# nmap's own Lua + LPeg over nse_main.lua's grammar (digest {digest}).\n")
        fh.write(r.stdout)
    print("m63 args: %d cases" % len(CASES))


if __name__ == "__main__":
    main()
