#!/usr/bin/env python3
"""Generate the M6.1 differential corpus and its golden verdicts.

The oracle is nmap's OWN Lua 5.4 interpreter, built from `liblua/` in this
repository, running loading logic sliced verbatim out of `nse_main.lua` (see
`extract_nse_main.py`). Nothing about how nmap reads `script.db` or extracts
`.nse` metadata is re-stated here; it is pasted in.

Emits, into the directory given as argv[1]:
    m6_scriptdb_cases.txt    the script.db corpus       (name, hex, note)
    m6_scriptdb_golden.txt   Lua's verdict + this port's (name, oracle, expected)
    m6_nse_cases.txt         the .nse corpus
    m6_nse_golden.txt        Lua's verdict + this port's
    m6_fixtures.rs           the same inputs as Rust consts, for the Miri-visible
                             unit tests (no filesystem under Miri)
"""

import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import extract_nse_main as E  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", "..", "..", ".."))
LUA = os.path.join(HERE, "lua")

# ---------------------------------------------------------------------------
# The oracle driver. Every `{block}` is verbatim `nse_main.lua`.
# ---------------------------------------------------------------------------

DRIVER = '''-- GENERATED by gen_m6_cases.py -- DO NOT EDIT.
--
-- The M6.1 differential oracle. Blocks marked "verbatim nse_main.lua" are
-- sliced out of the shipped file by anchor line and pasted in unchanged; the
-- provenance digest below covers all of them. Everything else is the driver
-- that feeds them a case and prints a verdict.
--
-- nse_main.lua provenance: {provenance}

local lines = io.lines
local yield, wrap = coroutine.yield, coroutine.wrap
local create, resume = coroutine.create, coroutine.resume
local match = string.match

-- verbatim nse_main.lua {script_rules_at}
{script_rules}

-- verbatim nse_main.lua {loadscript_at}
{loadscript}

local function metadata (filename)
  -- verbatim nse_main.lua {required_fields_at}
{required_fields}

  local script_closure_generator = loadscript(filename);
  local short_basename = match(filename, "([^/\\\\]+)%.nse$") or filename;

  -- verbatim nse_main.lua {env_at}
{env}

  -- DRIVER: nse_main.lua distinguishes a `require` failure (returns nil) from
  -- any other load failure (errors). `require` is not wired up in this oracle,
  -- so every failure is surfaced the same way. M6.1 does not port `require`.
  if not status then error(e, 0) end

  -- verbatim nse_main.lua {validate_at}
{validate}
  end

  return env, rules
end

local function database (text)
  local entries = {{}}
  local script_database = {{}}
  script_database.Entry = function (script_entry)
    -- verbatim nse_main.lua {db_entry_head_at}
{db_entry_head}
    for i, category in ipairs(categories) do
      -- verbatim nse_main.lua {db_category_assert_at}
{db_category_assert}
    end
    entries[#entries + 1] = {{filename = filename, categories = categories}}
  end
  -- nse_main.lua:1310 loads the file exactly this way.
  local chunk, err = load(text, "script.db", "t", script_database)
  if not chunk then error("loadfile: " .. tostring(err), 0) end
  chunk()
  return entries
end

-- ---------------------------------------------------------------------------
-- Driver
-- ---------------------------------------------------------------------------

local function esc (s)
  return (string.gsub(tostring(s), "[^%w%.%-_/ ]", function (c)
    return string.format("%%%02X", string.byte(c))
  end))
end

local function classify (msg)
  msg = tostring(msg)
  if string.find(msg, "loadfile:", 1, true) then return "SYNTAX" end
  if string.find(msg, "script database appears corrupt", 1, true) then return "CORRUPT_ENTRY" end
  if string.find(msg, "bad entry in script database", 1, true) then return "BAD_CATEGORY" end
  if string.find(msg, "is missing required field", 1, true) then return "MISSING_FIELD" end
  if string.find(msg, "is of improper type", 1, true) then return "BAD_TYPE" end
  if string.find(msg, "must be a function", 1, true) then return "BAD_RULE_TYPE" end
  if string.find(msg, "is missing required function", 1, true) then return "MISSING_RULE" end
  if string.find(msg, "non%-string entries in the 'categories'") then return "BAD_CATEGORY" end
  if string.find(msg, "non%-string entries in the 'dependencies'") then return "BAD_DEPENDENCY" end
  return "RUNTIME"
end

local mode, path = ...
local ok, res, extra = pcall(function ()
  if mode == "db" then
    local fh = assert(io.open(path, "rb"))
    local text = fh:read("a"); fh:close()
    return database(text)
  else
    return metadata(path)
  end
end)

if not ok then
  io.write("LUA_ERR:", classify(res), "\\n")
  os.exit(0)
end

if mode == "db" then
  local out = {{}}
  for i, e in ipairs(res) do
    local cats = {{}}
    for j, c in ipairs(e.categories) do cats[j] = esc(c) end
    out[i] = esc(e.filename) .. "=" .. table.concat(cats, ",")
  end
  io.write("LUA_OK:", table.concat(out, "|"), "\\n")
else
  local env, rules = res, extra
  local function arr (t)
    local o = {{}}
    for i, v in ipairs(t) do o[i] = esc(v) end
    return table.concat(o, ",")
  end
  local rnames = {{}}
  for _, r in ipairs({{"prerule", "hostrule", "portrule", "postrule"}}) do
    if rules[r] then rnames[#rnames + 1] = r end
  end
  io.write("LUA_OK:",
    "cats=", arr(rawget(env, "categories")),
    ";deps=", arr(rawget(env, "dependencies")),
    ";rules=", table.concat(rnames, ","),
    ";desc=", esc(rawget(env, "description") or ""),
    ";author=", esc(rawget(env, "author") or ""),
    ";license=", esc(rawget(env, "license") or ""),
    "\\n")
end
'''


def build_driver():
    blocks = E.extract(ROOT)
    fields = {"provenance": E.provenance(blocks)}
    for name, (text, first, last) in blocks.items():
        fields[name] = text
        fields[f"{name}_at"] = f"{first}-{last}" if first != last else str(first)
    return DRIVER.format(**fields)


# ---------------------------------------------------------------------------
# The corpus
# ---------------------------------------------------------------------------

E1 = 'Entry { filename = "a.nse", categories = { "safe", } }\n'

DB_CASES = [
    ("single", E1, "the canonical generated form"),
    ("two", E1 + 'Entry { filename = "b.nse", categories = { "auth", "safe", } }\n', "two records"),
    ("no_trailing_comma", 'Entry { filename = "a.nse", categories = { "safe" } }\n', "trailing comma is optional in Lua"),
    ("empty_categories", 'Entry { filename = "a.nse", categories = { } }\n', "a script in no category"),
    ("no_trailing_newline", E1.rstrip("\n"), "final LF is optional"),
    ("crlf", E1.replace("\n", "\r\n"), "CRLF line endings"),
    ("extra_whitespace", 'Entry\n\t{\n  filename\n =\n "a.nse"\n ,\n categories\n = {\n "safe"\n,\n}\n}\n', "whitespace is insignificant to Lua"),
    ("leading_comment", '-- generated by nmap\n' + E1, "line comment before the record"),
    ("trailing_comment", E1 + '-- end\n', "line comment after the record"),
    ("inline_comment", 'Entry { filename = "a.nse", --[[why]] categories = { "safe", } }\n', "block comment inside the table"),
    ("long_comment", '--[==[\nnot code\n]==]\n' + E1, "long-bracket comment"),
    ("empty_file", "", "an empty database is zero entries, not an error"),
    ("only_whitespace", "\n\n \t\n", "whitespace-only database"),
    ("only_comment", "-- nothing here\n", "comment-only database"),
    ("single_quotes", "Entry { filename = 'a.nse', categories = { 'safe', } }\n", "Lua accepts either quote"),
    ("escaped_quote", 'Entry { filename = "a\\"b.nse", categories = { "safe", } }\n', "escaped double quote in a filename"),
    ("escaped_backslash", 'Entry { filename = "a\\\\b.nse", categories = { "safe", } }\n', "escaped backslash"),
    ("escape_newline", 'Entry { filename = "a\\nb.nse", categories = { "safe", } }\n', "a newline inside a filename"),
    ("escape_tab", 'Entry { filename = "a\\tb.nse", categories = { "safe", } }\n', "a tab inside a filename"),
    ("decimal_escape", 'Entry { filename = "\\65.nse", categories = { "safe", } }\n', "decimal byte escape"),
    ("decimal_escape_3", 'Entry { filename = "\\065.nse", categories = { "safe", } }\n', "3-digit decimal escape"),
    ("hex_escape", 'Entry { filename = "\\x41.nse", categories = { "safe", } }\n', "hex byte escape"),
    ("unicode_escape", 'Entry { filename = "\\u{263A}.nse", categories = { "safe", } }\n', "UTF-8 escape"),
    ("z_escape", 'Entry { filename = "a\\z\n        b.nse", categories = { "safe", } }\n', "\\z eats following whitespace"),
    ("long_string_filename", 'Entry { filename = [[a.nse]], categories = { "safe", } }\n', "long-bracket string literal"),
    ("nul_in_filename", 'Entry { filename = "a\\0b.nse", categories = { "safe", } }\n', "NUL is a legal Lua string byte"),
    ("high_bytes", 'Entry { filename = "\\xC3\\xA9.nse", categories = { "safe", } }\n', "non-ASCII filename bytes"),
    ("missing_filename", 'Entry { categories = { "safe", } }\n', "no filename field"),
    ("missing_categories", 'Entry { filename = "a.nse" }\n', "no categories field"),
    ("filename_not_string", 'Entry { filename = 42, categories = { "safe", } }\n', "filename must be a string"),
    ("filename_nil", 'Entry { filename = nil, categories = { "safe", } }\n', "explicit nil filename"),
    ("categories_not_table", 'Entry { filename = "a.nse", categories = "safe" }\n', "categories must be a table"),
    ("category_not_string", 'Entry { filename = "a.nse", categories = { 42, } }\n', "a numeric category"),
    ("category_bool", 'Entry { filename = "a.nse", categories = { true, } }\n', "a boolean category"),
    ("nested_category", 'Entry { filename = "a.nse", categories = { { "x" }, } }\n', "a table where a category belongs"),
    ("extra_field", 'Entry { filename = "a.nse", categories = { "safe", }, extra = 1 }\n', "an unknown field is ignored by the C"),
    ("positional_field", 'Entry { "x", filename = "a.nse", categories = { "safe", } }\n', "a positional value alongside the named ones"),
    ("duplicate_filename_key", 'Entry { filename = "a.nse", filename = "b.nse", categories = { "safe", } }\n', "a repeated key"),
    ("sparse_categories", 'Entry { filename = "a.nse", categories = { [2] = "safe" } }\n', "ipairs stops before index 2"),
    ("explicit_index_categories", 'Entry { filename = "a.nse", categories = { [1] = "safe" } }\n', "an explicitly indexed category"),
    ("empty_filename", 'Entry { filename = "", categories = { "safe", } }\n', "an empty filename"),
    ("empty_category", 'Entry { filename = "a.nse", categories = { "", } }\n', "an empty category name"),
    ("syntax_unclosed", 'Entry { filename = "a.nse", categories = { "safe", }\n', "unterminated table"),
    ("syntax_bad_token", 'Entry { filename = = "a.nse" }\n', "a stray token"),
    ("syntax_unterminated_string", 'Entry { filename = "a.nse, categories = {} }\n', "unterminated string literal"),
    ("not_entry_call", 'local x = 1\n', "valid Lua that defines no entry"),
    ("unknown_global_call", 'Foo { filename = "a.nse" }\n', "calling something the environment does not define"),
    ("entry_string_arg", 'Entry "a.nse"\n', "Entry called with a string"),
    ("entry_no_arg", 'Entry()\n', "Entry called with nothing"),
    ("loop_generates_entries", 'for i = 1, 3 do Entry { filename = "s" .. i .. ".nse", categories = { "safe", } } end\n', "DIVERGENCE: arbitrary Lua, not the generated grammar"),
    ("conditional_entry", 'if 1 < 2 then\n' + E1 + 'end\n', "DIVERGENCE: arbitrary Lua, not the generated grammar"),
    ("entry_rebound", 'local E = Entry\nE { filename = "a.nse", categories = { "safe", } }\n', "DIVERGENCE: arbitrary Lua, not the generated grammar"),
    ("runtime_error", 'error("boom")\n', "a database that raises"),
    ("long_filename", 'Entry { filename = "' + ("a" * 4096) + '.nse", categories = { "safe", } }\n', "a 4 KiB filename"),
    ("many_categories", 'Entry { filename = "a.nse", categories = { ' + "".join('"c%d", ' % i for i in range(50)) + '} }\n', "50 categories on one record"),
    ("many_entries", "".join('Entry { filename = "s%d.nse", categories = { "safe", } }\n' % i for i in range(100)), "100 records"),
    ("shebang", '#!/usr/bin/lua\n' + E1, "a leading shebang line"),
    ("utf8_bom", '﻿' + E1, "a UTF-8 byte-order mark"),
]

NSE_MIN = 'categories = {"safe"}\ndependencies = {}\nportrule = function() end\naction = function() end\n'

NSE_CASES = [
    ("minimal", NSE_MIN, "the smallest loadable script"),
    ("defaults", 'action = function() end\nportrule = function() end\n', "categories and dependencies default to {} in the env"),
    ("full_metadata", 'description = "a description"\nauthor = "an author"\nlicense = "a license"\ncategories = {"safe", "discovery"}\ndependencies = {"dep1", "dep2"}\nhostrule = function() end\naction = function() end\n', "every metadata field set"),
    ("long_string_description", 'description = [[\nline one\nline two\n]]\n' + NSE_MIN, "a long-bracket description"),
    ("missing_action", 'categories = {"safe"}\ndependencies = {}\nportrule = function() end\n', "action is required"),
    ("action_not_function", 'categories = {"safe"}\ndependencies = {}\nportrule = function() end\naction = "not a function"\n', "action must be a function"),
    ("categories_not_table", 'categories = "safe"\ndependencies = {}\nportrule = function() end\naction = function() end\n', "categories must be a table"),
    ("dependencies_not_table", 'categories = {"safe"}\ndependencies = "dep"\nportrule = function() end\naction = function() end\n', "dependencies must be a table"),
    ("no_rule", 'categories = {"safe"}\ndependencies = {}\naction = function() end\n', "at least one rule is required"),
    ("prerule_only", 'categories = {"safe"}\ndependencies = {}\nprerule = function() end\naction = function() end\n', "prerule alone is enough"),
    ("postrule_only", 'categories = {"safe"}\ndependencies = {}\npostrule = function() end\naction = function() end\n', "postrule alone is enough"),
    ("hostrule_only", 'categories = {"safe"}\ndependencies = {}\nhostrule = function() end\naction = function() end\n', "hostrule alone is enough"),
    ("all_four_rules", 'categories = {"safe"}\ndependencies = {}\nprerule = function() end\nhostrule = function() end\nportrule = function() end\npostrule = function() end\naction = function() end\n', "all four rules"),
    ("rule_not_function", 'categories = {"safe"}\ndependencies = {}\nportrule = "nope"\naction = function() end\n', "a rule must be a function"),
    ("rule_nil", 'categories = {"safe"}\ndependencies = {}\nportrule = nil\nhostrule = function() end\naction = function() end\n', "an explicitly nil rule is allowed"),
    ("category_not_string", 'categories = {42}\ndependencies = {}\nportrule = function() end\naction = function() end\n', "a numeric category"),
    ("dependency_not_string", 'categories = {"safe"}\ndependencies = {42}\nportrule = function() end\naction = function() end\n', "a numeric dependency"),
    ("duplicate_categories", 'categories = {"safe", "discovery"}\nauthor = "x"\ncategories = {"safe", "discovery"}\ndependencies = {}\nportrule = function() end\naction = function() end\n', "the cups-queue-info.nse pattern: assigned twice"),
    ("duplicate_differing", 'categories = {"safe"}\ncategories = {"intrusive"}\ndependencies = {}\nportrule = function() end\naction = function() end\n', "assigned twice with different values: last wins"),
    ("local_categories", 'local categories = {"safe"}\ndependencies = {}\nportrule = function() end\naction = function() end\n', "a local shadows nothing in the env; the default {} is used"),
    ("categories_after_action", 'action = function() end\nportrule = function() end\ndependencies = {}\ncategories = {"safe"}\n', "declaration order does not matter"),
    ("empty_categories", 'categories = {}\ndependencies = {}\nportrule = function() end\naction = function() end\n', "an explicitly empty categories list"),
    ("crlf", NSE_MIN.replace("\n", "\r\n"), "CRLF line endings"),
    ("comment_only", '-- nothing\n', "a script that defines nothing"),
    ("empty_file", "", "an empty script"),
    ("syntax_error", 'categories = {"safe"\n', "unterminated table"),
    ("unicode_metadata", 'description = "caf\\u{00E9}"\n' + NSE_MIN, "non-ASCII metadata"),
    ("computed_categories", 'categories = {"sa" .. "fe"}\ndependencies = {}\nportrule = function() end\naction = function() end\n', "DIVERGENCE: categories built by an expression"),
    ("categories_from_call", 'categories = (function() return {"safe"} end)()\ndependencies = {}\nportrule = function() end\naction = function() end\n', "DIVERGENCE: categories returned by a call"),
    ("categories_via_table_insert", 'categories = {}\ntable.insert(categories, "safe")\ndependencies = {}\nportrule = function() end\naction = function() end\n', "DIVERGENCE: categories mutated after assignment"),
    ("side_effect_on_load", 'local t = os.time()\n' + NSE_MIN, "the C runs this at load time; the port never does"),
]

#: Cases where this port deliberately refuses what Lua accepts. The value is the
#: reason, copied into DIVERGENCES.md.
DB_DIVERGENCES = {
    "loop_generates_entries": "arbitrary Lua control flow",
    "conditional_entry": "arbitrary Lua control flow",
    "entry_rebound": "arbitrary Lua control flow",
    "not_entry_call": "a statement that is not an Entry record",
}
NSE_DIVERGENCES = {
    "computed_categories": "metadata is read, not evaluated",
    "categories_from_call": "metadata is read, not evaluated",
    "categories_via_table_insert": "metadata is read, not evaluated",
}


# ---------------------------------------------------------------------------
# Running the oracle and emitting the corpus
# ---------------------------------------------------------------------------

HEADER_CASES = "# name\t{}_hex\tnote\n# Generated by oracle/gen_m6_cases.py. Do not edit by hand.\n"
HEADER_GOLDEN = (
    "# name\toracle\texpected\n"
    "# `oracle` is the verdict of nmap's OWN Lua 5.4, built from liblua/ and\n"
    "# running loading logic sliced verbatim out of nse_main.lua.\n"
    "# A row whose two columns disagree is a deliberate divergence, ledgered in\n"
    "# DIVERGENCES.md: the C accepts it and this port refuses it, on purpose.\n"
)


def run_oracle(driver, mode, payload, work):
    """Feed one case to the Lua oracle; return its verdict line."""
    path = os.path.join(work, "case.nse" if mode == "nse" else "case.db")
    with open(path, "wb") as fh:
        fh.write(payload)
    proc = subprocess.run(
        [LUA, driver, mode, path],
        capture_output=True, text=True, timeout=60, cwd=work,
    )
    out = proc.stdout.strip()
    if not out.startswith("LUA_"):
        raise RuntimeError(f"oracle produced no verdict: {proc.stdout!r} {proc.stderr!r}")
    return out


def expected_for(name, oracle, divergences):
    """What this port must do: mirror Lua, except where we refuse on purpose."""
    if name in divergences:
        return "REJECT"
    return "ACCEPT:" + oracle[len("LUA_OK:"):] if oracle.startswith("LUA_OK:") else "REJECT"


def emit(out_dir, work, driver_path):
    written = []
    for kind, cases, divergences, mode in (
        ("scriptdb", DB_CASES, DB_DIVERGENCES, "db"),
        ("nse", NSE_CASES, NSE_DIVERGENCES, "nse"),
    ):
        rows, golden = [], []
        for name, text, note in cases:
            payload = text.encode("utf-8")
            oracle = run_oracle(driver_path, mode, payload, work)
            rows.append(f"{name}\t{payload.hex()}\t{note}")
            golden.append(f"{name}\t{oracle}\t{expected_for(name, oracle, divergences)}")
        cp = os.path.join(out_dir, f"m6_{kind}_cases.txt")
        gp = os.path.join(out_dir, f"m6_{kind}_golden.txt")
        with open(cp, "w", encoding="utf-8") as fh:
            fh.write(HEADER_CASES.format("db" if mode == "db" else "src"))
            fh.write("\n".join(rows) + "\n")
        with open(gp, "w", encoding="utf-8") as fh:
            fh.write(HEADER_GOLDEN)
            fh.write("\n".join(golden) + "\n")
        written += [cp, gp]
    return written


FIXTURE_HEAD = '''// GENERATED by tests/differential/m6/oracle/gen_m6_cases.py. Do not edit.
//
// The same inputs as the differential corpus, as Rust consts, so the unit tests
// in `core::nse::script` can exercise them under Miri — where there is no
// filesystem to read the corpus from. `regen_m6.sh --check` re-derives this file,
// which is what stops the Miri-visible tests from drifting away from the oracle.

/// `(name, input, expected)` for the script.db grammar. `expected` is
/// `ACCEPT:<serialized>` or `REJECT`, exactly as the golden file records it.
pub const SCRIPTDB_CASES: &[(&str, &[u8], &str)] = &[
'''


def emit_fixtures(out_dir, rows_db, rows_nse):
    def lit(b):
        return "&[" + ", ".join(str(x) for x in b) + "]"

    parts = [FIXTURE_HEAD]
    for name, payload, expected in rows_db:
        parts.append(f'    ("{name}", {lit(payload)}, "{expected}"),\n')
    parts.append("];\n\n")
    parts.append(
        "/// `(name, source, expected)` for `.nse` metadata extraction.\n"
        "pub const NSE_CASES: &[(&str, &[u8], &str)] = &[\n"
    )
    for name, payload, expected in rows_nse:
        parts.append(f'    ("{name}", {lit(payload)}, "{expected}"),\n')
    parts.append("];\n")
    path = os.path.join(out_dir, "m6_fixtures.rs")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("".join(parts))
    return path


def main():
    out_dir = sys.argv[1]
    os.makedirs(out_dir, exist_ok=True)
    work = os.path.join(out_dir, "_work")
    os.makedirs(work, exist_ok=True)

    driver_path = os.path.join(work, "nse_oracle.lua")
    with open(driver_path, "w", encoding="utf-8") as fh:
        fh.write(build_driver())

    collected = {}
    for kind, cases, divergences, mode in (
        ("scriptdb", DB_CASES, DB_DIVERGENCES, "db"),
        ("nse", NSE_CASES, NSE_DIVERGENCES, "nse"),
    ):
        rows = []
        for name, text, _note in cases:
            payload = text.encode("utf-8")
            oracle = run_oracle(driver_path, mode, payload, work)
            rows.append((name, payload, expected_for(name, oracle, divergences)))
        collected[kind] = rows

    written = emit(out_dir, work, driver_path)
    written.append(emit_fixtures(out_dir, collected["scriptdb"], collected["nse"]))
    for p in written:
        print(os.path.basename(p))


if __name__ == "__main__":
    main()
