#!/usr/bin/env python3
"""Emit a cross-product arithmetic corpus for the vendored Lua VM.

The hand-written M6.0 semantics corpus covers arithmetic by example, which is
how the two modulus panics were found -- but examples only ever find what
someone thought to write down. Integer arithmetic over a 64-bit domain has a
small, enumerable set of *interesting* operands (the range edges, the signs,
zero, the identity and its negation), and the interesting bugs live almost
entirely at their combinations: `i64::MIN % -1` traps, `-1 % i64::MIN`
overflows the correction term, `i64::MIN // -1` must wrap rather than trap.

So this emits the full cross product instead. Both operand lists include every
value whose combination is known to be a trap site in Rust, a special case in
PUC-Lua's `lvm.c`, or both -- and the product is small enough (a few hundred
cases per operator) to check exhaustively rather than sample.

Floats get the same treatment over infinities, zeroes and NaN, because
`luai_nummod`'s sign correction behaves differently from the obvious
`((a % b) + b) % b` formula at exactly those points.
"""
from __future__ import annotations

import sys

I64_MAX = 2**63 - 1
I64_MIN = -(2**63)

# Every one of these is here for a reason, not for coverage's sake:
#   0, -1      the two `luaV_mod` special cases
#   MIN, MAX   the trap sites for `%`, `//` and unary minus
#   MIN+1, MAX-1   their neighbours, to catch an off-by-one in a guard
#   1, -1      identity and negation, where wrapping and trapping agree
#   2, -2, 3, -3, 7, -7   small magnitudes in both signs, for the sign rules
#   2**32      a value that overflows on multiply but not add
INTS = [0, 1, -1, 2, -2, 3, -3, 7, -7, 2**32, -(2**32), I64_MAX, I64_MIN, I64_MAX - 1, I64_MIN + 1]

FLOATS = [
    "0.0", "-0.0", "1.0", "-1.0", "2.5", "-2.5", "5.0", "-5.0",
    "3.0", "-3.0", "math.huge", "-math.huge", "0/0", "1e308", "-1e308",
]

# Shift counts: inside the word, at the boundary, past it, and negative (which
# Lua defines as reversing direction and piccolo currently refuses).
SHIFTS = [0, 1, 31, 32, 63, 64, 65, 127, -1, -31, -63, -64, -65, I64_MAX, I64_MIN]

BINOPS = ["%", "//", "+", "-", "*", "&", "|", "~"]


def lit(v: int) -> str:
    # Lua has no negative literals -- `-9223372036854775808` lexes as unary
    # minus applied to a value one past maxinteger, which is a FLOAT. Writing
    # the range edges via math.mininteger/maxinteger keeps them integers.
    if v == I64_MIN:
        return "math.mininteger"
    if v == I64_MAX:
        return "math.maxinteger"
    if v == I64_MIN + 1:
        return "(math.mininteger + 1)"
    if v == I64_MAX - 1:
        return "(math.maxinteger - 1)"
    if v < 0:
        return f"({v})"
    return str(v)


def main() -> int:
    out = sys.stdout
    out.write("# name\tchunk_hex\tnote\n")
    out.write("# Generated by oracle/gen_m60_arith.py. Do not edit by hand.\n")
    seen: set[str] = set()

    def emit(name: str, chunk: str, note: str) -> None:
        if name in seen:
            raise SystemExit(f"duplicate case name: {name}")
        seen.add(name)
        out.write("%s\t%s\t%s\n" % (name, chunk.encode("utf-8").hex(), note))

    for op in BINOPS:
        opname = {"%": "mod", "//": "idiv", "+": "add", "-": "sub",
                  "*": "mul", "&": "band", "|": "bor", "~": "bxor"}[op]
        for i, a in enumerate(INTS):
            for j, b in enumerate(INTS):
                # `%` and `//` by zero are Lua errors; keep them, as "is this an
                # error" is itself behaviour worth pinning, but take only the
                # boolean so the message text does not enter the golden.
                if op in ("%", "//") and b == 0:
                    chunk = f"return (pcall(function() return {lit(a)} {op} {lit(b)} end))"
                    note = f"{a} {op} 0 is a catchable Lua error"
                else:
                    chunk = f"return {lit(a)} {op} {lit(b)}"
                    note = f"{a} {op} {b}"
                emit(f"i_{opname}_{i}_{j}", chunk, note)

    for i, a in enumerate(INTS):
        for j, sh in enumerate(SHIFTS):
            emit(f"i_shl_{i}_{j}", f"return {lit(a)} << {lit(sh)}", f"{a} << {sh}")
            emit(f"i_shr_{i}_{j}", f"return {lit(a)} >> {lit(sh)}", f"{a} >> {sh}")

    for i, a in enumerate(INTS):
        emit(f"i_unm_{i}", f"return -({lit(a)})", f"unary minus on {a}")
        emit(f"i_bnot_{i}", f"return ~({lit(a)})", f"bitwise not of {a}")

    for op, opname in (("%", "mod"), ("//", "idiv"), ("/", "div")):
        for i, a in enumerate(FLOATS):
            for j, b in enumerate(FLOATS):
                emit(f"f_{opname}_{i}_{j}", f"return ({a}) {op} ({b})", f"{a} {op} {b}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
