"""Generate the M6.2 differential corpus: the `--script` selection grammar.

The oracle is nmap's own Lua 5.4.8 AND nmap's own LPeg, both compiled from this
repository by `build_lua_oracle.sh`, running the selection grammar sliced
verbatim out of `nse_main.lua` and `nselib/lpeg-utility.lua` by
`extract_nse_main.py`. Nothing about how a `--script` expression is parsed or
evaluated is restated here.

That matters more for M6.2 than it did for M6.1. The grammar's observable
behaviour is a property of LPeg specifically — ordered choice, possessive
repetition that never gives characters back, capture functions that run only
after the whole match succeeds, and a backtrack stack that gives out at a
startlingly shallow nesting depth. A hand-written oracle would encode what a
PEG "should" do and quietly bless the same wrong answers as the port.

Only the CASES below are ours: inputs chosen to pin the corners.
"""

import hashlib
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import extract_nse_main as ex  # noqa: E402

# The blocks this generator pastes, in dependency order.
M62_BLOCKS = [
    "caselessp",
    "caseless",
    "keyword",
    "grammar",
    "globs",
    "entry_match",
    "rule_normalise",
]


def build_driver(root):
    """Emit the Lua oracle driver, with the grammar pasted in verbatim."""
    blocks = ex.extract(root)
    missing = [n for n in M62_BLOCKS if n not in blocks]
    if missing:
        raise ex.ExtractError(f"missing blocks: {missing}")
    digest = ex.provenance(blocks)

    def text(name):
        return blocks[name][0]

    def where(name):
        _, first, last = blocks[name]
        src = ex.LPEG_UTILITY if name in ex.LPEG_UTILITY_BLOCKS else ex.NSE_MAIN
        return f"{src}:{first}-{last}"

    parts = [
        "-- GENERATED by oracle/gen_m62_cases.py. Do not edit.\n",
        "--\n",
        "-- Every block below marked VERBATIM is pasted byte for byte out of the\n",
        "-- nmap sources named beside it. Provenance digest over all extracted\n",
        f"-- blocks: {digest}\n",
        "--\n",
        "-- This driver is the M6.2 oracle: nmap's own Lua running nmap's own LPeg\n",
        "-- over nmap's own selection grammar.\n\n",
        'local lpeg = require "lpeg"\n',
        "local locale, P, R, S, V, Cc = lpeg.locale, lpeg.P, lpeg.R, lpeg.S, lpeg.V, lpeg.Cc\n",
        "local match, gsub, find = string.match, string.gsub, string.find\n",
        "local lower, upper = string.lower, string.upper\n",
        "local assert, ipairs, pcall, setmetatable = assert, ipairs, pcall, setmetatable\n",
        "local tostring, tonumber, type = tostring, tonumber, type\n\n",
        # `caseless` lives in lpeg-utility, which pulls in stdnse -> the `nmap`
        # module, which only exists inside a running nmap process. Rather than
        # stub `nmap` (and risk the stub deciding the answer), the two functions
        # the grammar actually uses are lifted verbatim and bound to `U` here.
        f"-- VERBATIM {where('caselessp')}\n",
        text("caselessp") + "\n\n",
        f"-- VERBATIM {where('caseless')}\n",
        text("caseless") + "\n\n",
        "local U = { caseless = caseless }\n\n",
        f"-- VERBATIM {where('keyword')}\n",
        text("keyword") + "\n\n",
    ]

    # The grammar and glob blocks are indented as they appear inside
    # `get_chosen_scripts`; pasting them at file scope is legal Lua and keeps
    # them byte-identical, which is the property that matters.
    parts += [
        f"-- VERBATIM {where('grammar')}\n",
        text("grammar") + "\n\n",
        f"-- VERBATIM {where('globs')}\n",
        text("globs") + "\n\n",
    ]

    # Per-case evaluation: bind `filename` and `categories`, paste the entry
    # wiring, run the rule.
    parts.append(
        """
-- Evaluate one rule against one script entry, exactly as
-- `script_database.Entry` does.
local function evaluate (rule, filename, categories)
"""
    )
    parts.append(f"  -- VERBATIM {where('entry_match')}\n")
    parts.append(text("entry_match") + "\n")
    parts.append(
        """
  local ok, res = pcall(function () return T:match(rule) end)
  if not ok then
    local msg = tostring(res)
    if find(msg, "too many pending calls/choices", 1, true) then
      return "ERROR:backtrack"
    end
    return "ERROR:other"
  end
  if res == nil then
    return "REJECT"                      -- not an expression at all
  end
  return ("ACCEPT:%s:%s"):format(tostring(not not res), tostring(selected_by_name))
end

-- Normalise one rule the way `get_chosen_scripts` does before matching:
-- strip surrounding whitespace and peel a leading "+" (forced).
local function normalise (raw)
  local rules = { raw }
  local used_rules, forced_rules = {}, {}
"""
    )
    parts.append(f"  -- VERBATIM {where('rule_normalise')}\n")
    parts.append(text("rule_normalise") + "\n")
    parts.append(
        """
  local out = rules[1]
  -- A rule that is empty after stripping is never entered into used_rules, and
  -- rules[i] keeps its ORIGINAL text.
  if used_rules[out] == nil then
    return "SKIP:" .. out
  end
  return ("RULE:%s:%s"):format(tostring(not not forced_rules[out]), out)
end

local function unhex (s)
  return (s:gsub("%x%x", function (b) return string.char(tonumber(b, 16)) end))
end

-- stdin: one case per line.
--   match<TAB>rule_hex<TAB>basename_hex<TAB>cat_hex,cat_hex,...
--   norm<TAB>rule_hex
for line in io.lines() do
  local kind, rest = line:match("^(%w+)\\t(.*)$")
  if kind == "match" then
    local rule_hex, base_hex, cats_hex = rest:match("^(%x*)\\t(%x*)\\t(.*)$")
    local cats = {}
    for c in cats_hex:gmatch("[^,]+") do cats[#cats+1] = unhex(c) end
    io.write(evaluate(unhex(rule_hex), unhex(base_hex), cats), "\\n")
  elseif kind == "norm" then
    io.write(normalise(unhex(rest)), "\\n")
  else
    error("bad case kind: " .. tostring(kind))
  end
end
"""
    )
    return "".join(parts), digest


# --------------------------------------------------------------------------
# Cases. `(name, rule, filename, [categories], note)`
#
# The third column is the index entry's FILENAME, not its basename: the C
# derives the basename from it (`nse_main.lua:765`), and that derivation is
# part of what this corpus tests.
#
# The categories list is what makes a bare word a category rather than a glob,
# so several cases below differ ONLY in that list.
# --------------------------------------------------------------------------
SAFE = ["default", "safe"]

MATCH_CASES = [
    # --- the ordinary paths -------------------------------------------------
    ("category", "safe", "http-title", SAFE, "a category the entry has"),
    ("category_absent", "safe", "http-brute", ["brute"],
     "the entry lacks it, so it falls through to a glob and fails"),
    ("name_exact", "http-title", "http-title", SAFE, "selected by name"),
    ("name_glob_suffix", "http-*", "http-title", SAFE, "trailing wildcard"),
    ("name_glob_prefix", "*-title", "http-title", SAFE, "leading wildcard"),
    ("name_glob_all", "*", "http-title", SAFE, "bare wildcard matches everything"),
    ("name_with_extension", "http-title.nse", "http-title", SAFE,
     "the .nse suffix is optional and stripped"),
    ("pseudo_category_all", "all", "anything", ["x"], "'all' matches every entry"),
    ("literal_true", "true", "whatever", [], "the true keyword"),
    ("literal_false", "false", "whatever", [], "the false keyword"),

    # --- case: keywords fold, globs do not ----------------------------------
    ("category_uppercase", "SAFE", "http-title", SAFE, "categories are caseless"),
    ("category_mixed", "SaFe", "http-title", SAFE, "categories are caseless"),
    ("glob_uppercase", "HTTP-TITLE", "http-title", SAFE,
     "globs are case-SENSITIVE, so this does not match"),
    ("keyword_and_upper", "safe AND safe", "http-title", SAFE, "AND folds"),
    ("keyword_or_upper", "zz OR safe", "http-title", SAFE, "OR folds"),
    ("keyword_not_upper", "NOT zz", "http-title", SAFE, "NOT folds"),
    ("keyword_true_upper", "TRUE", "whatever", [], "TRUE folds"),
    ("keyword_all_upper", "ALL", "whatever", ["x"], "ALL folds"),

    # --- grouping: the right operand extends as far as it can ---------------
    # a=F b=F c=T. Conventional precedence gives (a and b) or c = true;
    # this grammar gives a and (b or c) = false.
    ("grouping_and_or", "a and b or c", "c", [], "decisive: and/or grouping"),
    ("grouping_or_and", "a or b and c", "a", [], "or with a right-side and"),
    ("grouping_parens", "(a and b) or c", "c", [], "explicit parens flip it back"),
    ("grouping_chain", "a or b or c", "c", [], "or chain"),
    ("grouping_and_chain", "a and b and c", "a", [], "and chain, first false"),
    ("not_binds_value", "not a and b", "b", [], "not takes a value, not an expression"),
    ("not_double", "not not a", "a", [], "stacked not"),
    ("paren_nested", "((safe))", "http-title", SAFE, "redundant parens"),
    ("paren_spaces", "( safe )", "http-title", SAFE, "spaces inside parens"),

    # --- the selected_by_name side effect -----------------------------------
    # A path that is evaluated sets the flag even when it does not decide the
    # result, and even when the result is false.
    ("byname_negated", "safe and not http-*", "http-title", SAFE,
     "matches by name, then is negated away: false, but by_name is set"),
    ("byname_not_only", "not http-*", "http-title", SAFE, "negated name match"),
    ("byname_or_short", "http-* or safe", "http-title", SAFE, "both branches run"),
    ("byname_or_miss", "zzz-* or safe", "http-title", SAFE,
     "the glob is evaluated but misses, so by_name stays false"),
    ("byname_and_false", "zzz and http-*", "http-title", SAFE,
     "left is false; the right glob still runs"),

    # --- the keyword follow-set ---------------------------------------------
    ("follow_nota", "nota", "nota", [], "'not' must be followed by space/()/,/EOF"),
    ("follow_notx_and", "notx and safe", "notx", ["safe"], "notx is a glob, not not-x"),
    ("follow_anda", "anda", "anda", [], "'and' needs the follow-set too"),
    ("follow_ora", "ora", "ora", [], "'or' needs the follow-set too"),
    ("follow_allx", "allx", "allx", [], "'all' needs the follow-set too"),
    ("follow_truex", "truex", "truex", [], "'true' needs the follow-set too"),
    ("follow_not_paren", "not(safe)", "http-title", SAFE, "'(' is in the follow-set"),

    # --- glob metacharacters: only '*' is a wildcard ------------------------
    ("glob_question", "http-titl?", "http-title", [], "'?' is literal, not any-char"),
    ("glob_dot", "http.title", "http-title", [], "'.' is literal"),
    ("glob_dot_literal", "http.title", "http.title", [], "'.' matches itself"),
    ("glob_plus", "a+b", "a+b", [], "'+' is escaped"),
    ("glob_percent", "a%b", "a%b", [], "'%' is escaped"),
    ("glob_bracket", "[ab]", "[ab]", [], "'[' ']' are escaped"),
    ("glob_caret", "^a", "^a", [], "'^' is escaped"),
    ("glob_dollar", "a$", "a$", [], "'$' is escaped"),
    ("glob_dash", "a-b", "a-b", [], "'-' is escaped"),
    ("glob_star_middle", "ht*le", "http-title", [], "wildcard in the middle"),
    ("glob_star_double", "**", "http-title", [], "two wildcards"),
    ("glob_anchored", "ttp-titl", "http-title", [], "globs are anchored at both ends"),
    ("glob_nse_once", "x.nse.nse", "x.nse", [], "only one trailing .nse is stripped"),
    ("glob_nse_middle", "a.nse.b", "a.nse.b", [], ".nse not at the end stays"),

    # --- structural rejects --------------------------------------------------
    ("reject_empty", "", "http-title", SAFE, "empty rule is not an expression"),
    ("reject_spaces", "   ", "http-title", SAFE, "whitespace only"),
    ("reject_open_paren", "safe(", "http-title", SAFE, "unbalanced"),
    ("reject_close_paren", "safe)", "http-title", SAFE, "unbalanced"),
    ("reject_empty_parens", "()", "http-title", SAFE, "no expression inside"),
    ("reject_trailing_and", "safe and", "http-title", SAFE, "dangling operator"),
    ("reject_leading_and", "and safe", "http-title", SAFE, "leading operator"),
    ("reject_double_or", "a or or b", "a", [], "doubled operator"),
    ("reject_bare_not", "not", "http-title", SAFE, "not with no operand"),
    ("reject_comma", "x,y", "x", ["x"],
     "',' is in the keyword follow-set but not in the path class"),

    # --- byte-range corners of the path character class ---------------------
    # R("\\033\\039", "\\042\\126") -- decimal, so 33..39 and 42..126.
    ("bytes_bang", "!", "!", [], "33, the low edge"),
    ("bytes_quote", "'", "'", [], "39, the top of the low run"),
    ("bytes_star_edge", "*", "*", [], "42, the bottom of the high run"),
    ("bytes_tilde", "~", "~", [], "126, the high edge"),
    ("bytes_tab", "\t", "\t", [], "9 is outside the class"),
    ("bytes_del", "\x7f", "\x7f", [], "127 is outside the class"),
    ("bytes_high", "\xc3\xa9", "\xc3\xa9", [], "non-ASCII is outside the class"),
    ("bytes_nul", "a\x00b", "a\x00b", [], "NUL is outside the class"),
    ("bytes_newline", "a\nb", "a\nb", [], "newline is space, so it splits"),
]

# --- basename derivation: the C reduces `filename` before any glob runs ------
for _name, _rule, _file, _note in (
    ("basename_plain", "http-title", "http-title.nse", "the .nse extension goes"),
    ("basename_dir", "http-title", "scripts/http-title.nse", "so does the directory"),
    ("basename_backslash", "http-title", "scripts\\http-title.nse", "backslash separates too"),
    ("basename_no_ext", "readme", "scripts/readme", "no extension to drop"),
    ("basename_double_ext", "x.nse", "x.nse.nse", "only one .nse is dropped"),
    ("basename_only_ext", "*", ".nse", "reduces to the empty name"),
    ("basename_ext_in_dir", "b", "a.nse/b", "a .nse that is not the extension"),
    ("basename_dot_dir", "b", "./b.nse", "relative path"),
):
    MATCH_CASES.append((_name, _rule, _file, [], _note))

# The C's backtrack stack gives out very early, and at a DIFFERENT length for
# each construct — 15 nested parens, 19 `and`s, 31 `or`s — because all three
# draw on one shared 100-slot stack (lpeg.c: MAXBACK). Bracket each threshold.
for _depth in (1, 5, 10, 13, 14, 15, 16, 40):
    MATCH_CASES.append(
        (
            f"nesting_{_depth}",
            "(" * _depth + "safe" + ")" * _depth,
            "http-title",
            SAFE,
            f"{_depth} levels of parentheses",
        )
    )
for _n in (2, 10, 18, 19, 25):
    MATCH_CASES.append(
        (
            f"and_chain_{_n}",
            " and ".join(["safe"] * _n),
            "http-title",
            SAFE,
            f"{_n}-term and chain",
        )
    )
for _n in (2, 10, 30, 31, 40):
    MATCH_CASES.append(
        (
            f"or_chain_{_n}",
            " or ".join(["zz"] * (_n - 1) + ["safe"]),
            "http-title",
            SAFE,
            f"{_n}-term or chain",
        )
    )

NORM_CASES = [
    ("norm_plain", "safe", "no prefix, no padding"),
    ("norm_forced", "+safe", "the '+' forced prefix"),
    ("norm_forced_spaced", "+ safe", "space between '+' and the rule"),
    ("norm_leading_ws", "   safe", "leading whitespace is stripped"),
    ("norm_trailing_ws", "safe   ", "trailing whitespace is stripped"),
    ("norm_both_ws", "  safe  ", "both sides"),
    ("norm_inner_ws", "a and b", "inner whitespace is preserved"),
    ("norm_ws_forced", "  +  safe  ", "padding around a forced rule"),
    ("norm_empty", "", "empty stays empty and is skipped"),
    ("norm_only_ws", "    ", "whitespace-only is skipped"),
    ("norm_only_plus", "+", "a bare '+' leaves nothing and is skipped"),
    ("norm_double_plus", "++safe", "only one '+' is peeled"),
    ("norm_plus_inside", "a+b", "'+' elsewhere is not a prefix"),
    ("norm_tab", "\tsafe\t", "tabs count as whitespace"),
    ("norm_newline", "\nsafe\n", "newlines count as whitespace"),
]

#: Cases where this port deliberately parts company with the C. Keyed by case
#: name -> (expected_verdict, why). Every entry is ledgered in DIVERGENCES.md
#: and pinned by name in `crates/core/tests/selection_differential.rs`.
DIVERGENCES = {
    # The C's ceiling is an LPeg backtrack-stack artifact (MAXBACK = 100,
    # divided by the per-level cost of this grammar), not a designed limit.
    # This port accepts every rule the C accepts and keeps going further.
    "nesting_15": ("ACCEPT:true:false", "the C's stack gives out at 15 nested parens"),
    "nesting_16": ("ACCEPT:true:false", "the C's stack gives out at 15 nested parens"),
    "nesting_40": ("ACCEPT:true:false", "the C's stack gives out at 15 nested parens"),
    "and_chain_19": ("ACCEPT:true:false", "the C's stack gives out at 19 `and`s"),
    "and_chain_25": ("ACCEPT:true:false", "the C's stack gives out at 19 `and`s"),
    "or_chain_31": ("ACCEPT:true:false", "the C's stack gives out at 31 `or`s"),
    "or_chain_40": ("ACCEPT:true:false", "the C's stack gives out at 31 `or`s"),
}

HEADER_CASES = (
    "# name\trule_hex\tfilename_hex\tcategories_hex\tnote\n"
    "# Generated by oracle/gen_m62_cases.py. Do not edit by hand.\n"
)
HEADER_NORM = (
    "# name\trule_hex\tnote\n"
    "# Generated by oracle/gen_m62_cases.py. Do not edit by hand.\n"
)
HEADER_GOLDEN = (
    "# name\toracle\texpected\n"
    "# `oracle` is the verdict of nmap's OWN Lua 5.4 and OWN LPeg, built from\n"
    "# liblua/ + lpeg.c, running the selection grammar sliced verbatim out of\n"
    "# nse_main.lua and nselib/lpeg-utility.lua.\n"
    "# A row whose two columns disagree is a deliberate divergence, ledgered in\n"
    "# DIVERGENCES.md and pinned by name in the differential test.\n"
)


def run_oracle(driver_path, stdin_text, lua):
    proc = subprocess.run(
        [lua, driver_path],
        input=stdin_text,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"oracle failed: {proc.stderr.strip()[:400]}")
    return proc.stdout.rstrip("\n").split("\n")


def emit(out_dir, driver_path, lua):
    match_stdin = "".join(
        "match\t{}\t{}\t{}\n".format(
            rule.encode("latin-1").hex(),
            base.encode("latin-1").hex(),
            ",".join(c.encode("latin-1").hex() for c in cats),
        )
        for _n, rule, base, cats, _note in MATCH_CASES
    )
    norm_stdin = "".join(
        "norm\t{}\n".format(rule.encode("latin-1").hex())
        for _n, rule, _note in NORM_CASES
    )

    match_out = run_oracle(driver_path, match_stdin, lua)
    norm_out = run_oracle(driver_path, norm_stdin, lua)
    if len(match_out) != len(MATCH_CASES):
        raise RuntimeError(f"oracle returned {len(match_out)} rows for {len(MATCH_CASES)} cases")
    if len(norm_out) != len(NORM_CASES):
        raise RuntimeError(f"oracle returned {len(norm_out)} rows for {len(NORM_CASES)} cases")

    cases, golden = [], []
    for (name, rule, base, cats, note), verdict in zip(MATCH_CASES, match_out):
        cases.append(
            "{}\t{}\t{}\t{}\t{}".format(
                name,
                rule.encode("latin-1").hex(),
                base.encode("latin-1").hex(),
                ",".join(c.encode("latin-1").hex() for c in cats),
                note,
            )
        )
        expected = DIVERGENCES.get(name, (verdict, None))[0]
        golden.append(f"{name}\t{verdict}\t{expected}")

    norms, norm_golden = [], []
    for (name, rule, note), verdict in zip(NORM_CASES, norm_out):
        norms.append("{}\t{}\t{}".format(name, rule.encode("latin-1").hex(), note))
        norm_golden.append(f"{name}\t{verdict}\t{verdict}")

    files = {
        "m62_cases.txt": HEADER_CASES + "\n".join(cases) + "\n",
        "m62_golden.txt": HEADER_GOLDEN + "\n".join(golden) + "\n",
        "m62_norm_cases.txt": HEADER_NORM + "\n".join(norms) + "\n",
        "m62_norm_golden.txt": HEADER_GOLDEN + "\n".join(norm_golden) + "\n",
    }
    files["m62_fixtures.rs"] = fixtures(cases, golden, norms, norm_golden)
    for name, body in files.items():
        with open(os.path.join(out_dir, name), "w", encoding="utf-8") as fh:
            fh.write(body)
    return len(MATCH_CASES), len(NORM_CASES)


def fixtures(cases, golden, norms, norm_golden):
    """The same inputs as Rust consts, for the Miri-visible unit tests."""

    def lit(hexstr):
        raw = bytes.fromhex(hexstr)
        return "&[" + ", ".join(str(b) for b in raw) + "]"

    out = [
        "// GENERATED by tests/differential/m6/oracle/gen_m62_cases.py. Do not edit.\n",
        "//\n",
        "// The same inputs as the M6.2 differential corpus, as Rust consts, so the\n",
        "// unit tests in `core::nse::selection` can exercise them under Miri — where\n",
        "// there is no filesystem to read the corpus from. `regen_m62.sh --check`\n",
        "// re-derives this file, which is what stops the Miri-visible tests from\n",
        "// drifting away from the oracle.\n\n",
        "/// One corpus row: the case name, the rule, the index entry's filename,\n",
        "/// its categories, and the verdict this port must reach. `expected` is\n",
        "/// `ACCEPT:<matched>:<by_name>`, `REJECT`, or `ERROR:<class>`, exactly as\n",
        "/// the golden file records it.\n",
        "pub type SelectionCase = (\n",
        "    &'static str,\n",
        "    &'static [u8],\n",
        "    &'static [u8],\n",
        "    &'static [&'static [u8]],\n",
        "    &'static str,\n",
        ");\n\n",
        "/// Every case in the M6.2 differential corpus.\n",
        "pub const SELECTION_CASES: &[SelectionCase] = &[\n",
    ]
    expected = {row.split("\t")[0]: row.split("\t")[2] for row in golden}
    for row in cases:
        name, rule_hex, base_hex, cats_hex, _note = row.split("\t")
        cats = "&[" + ", ".join(lit(c) for c in cats_hex.split(",") if c) + "]"
        out.append(
            f'    ("{name}", {lit(rule_hex)}, {lit(base_hex)}, {cats}, "{expected[name]}"),\n'
        )
    out.append("];\n\n")
    out += [
        "/// `(name, raw_rule, expected)` for rule normalisation. `expected` is\n",
        "/// `RULE:<forced>:<text>` or `SKIP:<original>`.\n",
        "pub const NORM_CASES: &[(&str, &[u8], &str)] = &[\n",
    ]
    nexpected = {row.split("\t")[0]: row.split("\t")[2] for row in norm_golden}
    for row in norms:
        name, rule_hex, _note = row.split("\t")
        out.append(f'    ("{name}", {lit(rule_hex)}, "{nexpected[name]}"),\n')
    out.append("];\n")
    return "".join(out)


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.abspath(os.path.join(here, "..", "..", "..", "..", ".."))
    # An explicit output directory lets regen_m62.sh generate into a scratch
    # dir and diff, so --check never touches the committed files.
    out_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.abspath(os.path.join(here, ".."))
    lua = os.path.join(here, "lua")

    driver, digest = build_driver(root)
    driver_path = os.path.join(here, "m62_driver.lua")
    with open(driver_path, "w", encoding="utf-8") as fh:
        fh.write(driver)

    n_match, n_norm = emit(out_dir, driver_path, lua)
    print(f"M6.2 corpus: {n_match} match cases, {n_norm} normalisation cases")
    print(f"provenance digest: {digest}")


if __name__ == "__main__":
    main()
