//! M6.1 conformance against real nmap output.
//!
//! `scripts/script.db` was generated by nmap itself: `--script-updatedb` loads
//! every `scripts/*.nse` through `Script.new`, which *executes* each script's
//! top level, and writes the categories it finds. That file is therefore a
//! golden record of the very extraction this module ports — produced by the
//! reference implementation, over the whole shipped corpus, and committed
//! upstream.
//!
//! So the test is: read all 611 scripts with `core::nse::script`, re-emit the
//! index in nmap's exact output format (`nse_main.lua:1336-1343`), and require
//! the result to equal the committed file byte for byte. It needs no Lua, and
//! it is a stronger statement than any synthetic corpus could make.
#![cfg(not(miri))] // reads the C tree from disk; Miri has no filesystem

use nmap_core::nse::script::{parse_nse_metadata, parse_script_db, Field};
use std::path::{Path, PathBuf};

fn tree_root() -> PathBuf {
    // crates/core -> crates -> nmap-rs -> the C tree
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(3)
        .expect("repository layout")
        .to_path_buf()
}

fn shipped_scripts(root: &Path) -> Vec<PathBuf> {
    let mut v: Vec<PathBuf> = std::fs::read_dir(root.join("scripts"))
        .expect("scripts/ is readable")
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|e| e == "nse"))
        .collect();
    v.sort();
    v
}

/// Re-derive `script.db` from the corpus and require it to match nmap's own.
#[test]
fn regenerating_script_db_reproduces_nmaps_own_index() {
    let root = tree_root();
    let scripts = shipped_scripts(&root);
    assert!(
        scripts.len() > 500,
        "expected the shipped corpus, found {} scripts",
        scripts.len()
    );

    let mut out = String::new();
    for path in &scripts {
        let src = std::fs::read(path).expect("script is readable");
        let meta = parse_nse_metadata(&src).unwrap_or_else(|e| panic!("{}: {e:?}", path.display()));
        let Field::Literal(cats) = meta.categories() else {
            panic!(
                "{}: categories are not statically determinable",
                path.display()
            );
        };

        // nse_main.lua:1337 sorts, then lowercases on output.
        let mut cats: Vec<String> = cats
            .iter()
            .map(|c| String::from_utf8(c.clone()).expect("category is UTF-8"))
            .collect();
        cats.sort();

        let base = path.file_name().expect("basename").to_string_lossy();
        out.push_str(&format!("Entry {{ filename = \"{base}\", categories = {{"));
        for c in &cats {
            out.push_str(&format!(" \"{}\",", c.to_lowercase()));
        }
        out.push_str(" } }\n");
    }

    let committed = std::fs::read_to_string(root.join("scripts/script.db"))
        .expect("scripts/script.db is readable");
    assert_eq!(
        out.len(),
        committed.len(),
        "regenerated index is {} bytes, nmap's is {}",
        out.len(),
        committed.len()
    );
    assert!(
        out == committed,
        "the regenerated index differs from nmap's own script.db"
    );
}

/// The committed index must round-trip through the parser unchanged.
#[test]
fn the_shipped_index_parses_and_round_trips() {
    let root = tree_root();
    let raw = std::fs::read(root.join("scripts/script.db")).expect("script.db is readable");
    let db = parse_script_db(&raw).expect("the shipped index parses");
    assert_eq!(db.entries().len(), shipped_scripts(&root).len());

    let mut out = String::new();
    for e in db.entries() {
        out.push_str(&format!(
            "Entry {{ filename = \"{}\", categories = {{",
            String::from_utf8_lossy(e.filename())
        ));
        for c in e.categories() {
            out.push_str(&format!(" \"{}\",", String::from_utf8_lossy(c)));
        }
        out.push_str(" } }\n");
    }
    assert!(
        out.as_bytes() == raw.as_slice(),
        "round trip changed the index"
    );
}

/// Every shipped script must yield determinate categories — the field that
/// decides whether it runs. `dependencies` is allowed one documented exception.
#[test]
fn every_shipped_script_has_determinate_gating_fields() {
    let root = tree_root();
    let mut indeterminate_deps = Vec::new();
    for path in shipped_scripts(&root) {
        let src = std::fs::read(&path).expect("script is readable");
        let meta = parse_nse_metadata(&src).unwrap_or_else(|e| panic!("{}: {e:?}", path.display()));
        assert!(
            meta.categories().is_literal(),
            "{}: categories must be readable without running the script",
            path.display()
        );
        if !meta.dependencies().is_literal() {
            indeterminate_deps.push(path.file_name().map(|s| s.to_string_lossy().into_owned()));
        }
    }
    // scripts/clock-skew.nse builds its `description` by concatenating its own
    // `dependencies`, so the name is mentioned outside its assignment and this
    // parser will not claim to know it is only read. Pinned so that a second
    // such script is a test failure and a deliberate decision, not a drift.
    let names: Vec<_> = indeterminate_deps.into_iter().flatten().collect();
    assert_eq!(
        names,
        vec!["clock-skew.nse".to_string()],
        "unexpected set of scripts with indeterminate dependencies"
    );
}
