//! M6.2 differential: `core::nse::selection` against nmap's own LPeg.
//!
//! The corpus and golden in `tests/differential/m6` are generated by running
//! the `--script` selection grammar — sliced verbatim out of `nse_main.lua` and
//! `nselib/lpeg-utility.lua` — under nmap's own Lua 5.4.8 and nmap's own LPeg,
//! both compiled from this repository. `regen_m62.sh --check` re-derives every
//! generated file on each CI run, so the golden cannot drift into agreeing with
//! the port.
//!
//! A row whose `oracle` and `expected` columns disagree is a deliberate
//! divergence. Every one is ledgered in `DIVERGENCES.md` and named in
//! [`EXPECTED_DIVERGENCES`] below, so a new one cannot appear without editing
//! this file.

#![cfg(not(miri))] // reads the corpus from disk; Miri has no filesystem

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use nmap_core::nse::selection::{matches, normalize, Entry, SelectionError};

/// The only cases where this port is expected to differ from the C.
///
/// All seven are the same divergence — `nse-selection-depth-ceiling` — seen
/// through three constructs. The C refuses deeply nested or long-chained rules
/// because LPeg's fixed 100-slot backtrack stack runs out, at 15 nested
/// parentheses, 19 chained `and`s or 31 chained `or`s. This port accepts them.
const EXPECTED_DIVERGENCES: &[&str] = &[
    "nesting_15",
    "nesting_16",
    "nesting_40",
    "and_chain_19",
    "and_chain_25",
    "or_chain_31",
    "or_chain_40",
];

fn corpus_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("repository layout")
        .join("tests/differential/m6")
}

fn rows(name: &str) -> Vec<Vec<String>> {
    let path = corpus_dir().join(name);
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("{}: {e} (run regen_m62.sh)", path.display()));
    text.lines()
        .filter(|l| !l.starts_with('#') && !l.is_empty())
        .map(|l| l.split('\t').map(str::to_owned).collect())
        .collect()
}

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i.saturating_add(2)], 16).expect("hex"))
        .collect()
}

/// Render a verdict in the golden file's vocabulary.
fn verdict(rule: &[u8], entry: &Entry<'_>) -> String {
    match matches(rule, entry) {
        Ok(s) => format!("ACCEPT:{}:{}", s.matched, s.by_name),
        Err(SelectionError::NotAnExpression) => "REJECT".to_owned(),
        Err(SelectionError::TooDeep) => "ERROR:depth".to_owned(),
        Err(SelectionError::TooLong) => "ERROR:length".to_owned(),
    }
}

#[test]
fn selection_matches_nmaps_own_lpeg() {
    let cases = rows("m62_cases.txt");
    let golden = rows("m62_golden.txt");
    assert_eq!(
        cases.len(),
        golden.len(),
        "corpus and golden are out of step"
    );
    assert!(cases.len() >= 90, "corpus shrank to {}", cases.len());

    for (case, gold) in cases.iter().zip(&golden) {
        let (name, rule_hex, file_hex, cats_hex) = (&case[0], &case[1], &case[2], &case[3]);
        assert_eq!(name, &gold[0], "corpus and golden are misaligned");

        let rule = unhex(rule_hex);
        let filename = unhex(file_hex);
        let cats: Vec<Vec<u8>> = cats_hex
            .split(',')
            .filter(|s| !s.is_empty())
            .map(unhex)
            .collect();
        let cat_refs: Vec<&[u8]> = cats.iter().map(Vec::as_slice).collect();
        let entry = Entry::from_filename(&filename, &cat_refs);

        assert_eq!(&verdict(&rule, &entry), &gold[2], "case {name}");
    }
}

#[test]
fn rule_normalisation_matches_nmaps_own_lua() {
    let cases = rows("m62_norm_cases.txt");
    let golden = rows("m62_norm_golden.txt");
    assert_eq!(
        cases.len(),
        golden.len(),
        "corpus and golden are out of step"
    );

    for (case, gold) in cases.iter().zip(&golden) {
        let (name, raw) = (&case[0], unhex(&case[1]));
        assert_eq!(name, &gold[0], "corpus and golden are misaligned");
        let got = match normalize(&raw) {
            Some(r) => format!(
                "RULE:{}:{}",
                r.forced,
                std::str::from_utf8(r.text).unwrap_or("<binary>")
            ),
            // When a rule normalises away the C never records it, and the
            // golden keeps the ORIGINAL text in the SKIP row.
            None => format!("SKIP:{}", std::str::from_utf8(&raw).unwrap_or("<binary>")),
        };
        assert_eq!(&got, &gold[2], "case {name}");
    }
}

/// The ledger is the contract: exactly these cases may differ from the C.
#[test]
fn no_unledgered_divergence_exists() {
    let golden = rows("m62_golden.txt");
    let found: BTreeSet<&str> = golden
        .iter()
        .filter(|r| r[1] != r[2])
        .map(|r| r[0].as_str())
        .collect();
    let expected: BTreeSet<&str> = EXPECTED_DIVERGENCES.iter().copied().collect();
    assert_eq!(
        found, expected,
        "the set of divergences changed; update DIVERGENCES.md and this test"
    );
}

/// Nothing the C refuses to parse is accepted here.
///
/// The port is allowed to accept rules the C rejects only for the ledgered
/// depth ceiling. For every other rejection the two must agree, because a rule
/// the C cannot parse is one it hands off to the filesystem as a filename —
/// accepting it here would silently change which scripts run.
#[test]
fn nothing_the_oracle_rejects_is_accepted_here() {
    let cases = rows("m62_cases.txt");
    let golden = rows("m62_golden.txt");
    let ledgered: BTreeSet<&str> = EXPECTED_DIVERGENCES.iter().copied().collect();

    let mut checked = 0;
    for (case, gold) in cases.iter().zip(&golden) {
        if gold[1] != "REJECT" || ledgered.contains(gold[0].as_str()) {
            continue;
        }
        let filename = unhex(&case[2]);
        let cats: Vec<Vec<u8>> = case[3]
            .split(',')
            .filter(|s| !s.is_empty())
            .map(unhex)
            .collect();
        let cat_refs: Vec<&[u8]> = cats.iter().map(Vec::as_slice).collect();
        let entry = Entry::from_filename(&filename, &cat_refs);
        assert!(
            matches(&unhex(&case[1]), &entry).is_err(),
            "case {}: the oracle rejects this rule but the port accepted it",
            gold[0]
        );
        checked += 1;
    }
    assert!(
        checked >= 10,
        "only {checked} rejection cases — corpus shrank"
    );
}
